# Generated by Django 4.1.dev20220131153740 on 2022-02-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('author', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
